apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: petclinic
  type: {{ .Values.petclinic.serviceType }}
  ports:
    - port: 80
      targetPort: 8080
