---
- name: Install required software packages on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update package list
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
