---
- name: Install required software packages on Ubuntu
  hosts: all
  become: yes
  tasks:
    # Update package list and upgrade packages
    - name: Update package list
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes

    # Install Git
    - name: Install Git
      ansible.builtin.apt:
        name: git
        state: present

    # Install Docker
    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Start Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    # Amazon SSM Agent Installation
    - name: Check if Amazon SSM Agent is installed via Snap
      ansible.builtin.command: snap list amazon-ssm-agent
      register: ssm_agent_snap_installed
      ignore_errors: yes

    - name: Install Amazon SSM Agent via Snap
      ansible.builtin.command: snap install amazon-ssm-agent --classic
      when: ssm_agent_snap_installed.rc != 0

    - name: Enable and Start Amazon SSM Agent (Snap version)
      ansible.builtin.systemd:
        name: snap.amazon-ssm-agent.amazon-ssm-agent
        state: started
        enabled: yes

    # Amazon CloudWatch Agent Installation
    - name: Download Amazon CloudWatch Agent for Ubuntu
      ansible.builtin.get_url:
        url: "https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb"
        dest: /tmp/amazon-cloudwatch-agent.deb

    - name: Install Amazon CloudWatch Agent
      ansible.builtin.apt:
        deb: /tmp/amazon-cloudwatch-agent.deb
        state: present

    - name: Start Amazon CloudWatch Agent
      ansible.builtin.command:
        cmd: "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a start"

    - name: Verify Amazon CloudWatch Agent status
      ansible.builtin.command:
        cmd: "/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -m ec2 -a status"
