name: CD - Login to Argo CD (LoadBalancer)

on:
  workflow_dispatch:

env:
  ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to ArgoCD (LoadBalancer)
        run: |
          argocd login https://$ARGOCD_SERVER --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }} --grpc-web --insecure
