name: Argo CD Login

on:
  workflow_dispatch: # Manually trigger the workflow
  push:
    branches:
      - main # Trigger on push to main branch

jobs:
  login-to-argocd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Argo CD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
          rm argocd-linux-amd64

      - name: Log in to Argo CD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }} 
          ARGOCD_USERNAME: "admin" # Default admin username
          ARGOCD_ADMIN_PASSWORD: ${{ secrets.ARGOCD_ADMIN_PASSWORD }}
        run: |
          argocd login $ARGOCD_SERVER \
            --username $ARGOCD_USERNAME \
            --password $ARGOCD_ADMIN_PASSWORD \
            --grpc-web \ # Use --grpc-web if the server is behind a proxy or load balancer
            --skip-test-tls # Skip testing whether the server is configured with TLS

      - name: Verify login
        run: |
          argocd app list
