name: CD - Deploy to Kubernetes with Argo CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI - Build & Push Spring PetClinic"]
    types:
      - completed

env:
  ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
  ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
  IMAGE_NAME: petclinic-app
  IMAGE_TAG: latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Login to ArgoCD
        run: |
          argocd login $ARGOCD_SERVER --username admin --password $ARGOCD_AUTH_TOKEN --insecure

      - name: Sync ArgoCD Application
        run: |
          argocd app sync petclinic
          argocd app wait petclinic --health --timeout 120
