name: Check ArgoCD Login

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  check-login:
    runs-on: ubuntu-latest

    steps:
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd

      - name: Login to ArgoCD
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        run: |
          argocd login $ARGOCD_SERVER --auth-token $ARGOCD_AUTH_TOKEN
          echo "Login successful!"

      - name: Logout from ArgoCD
        run: argocd logout $ARGOCD_SERVER
